name: Build of the project
on:
  push:
    paths-ignore:
      - "README.md"
      - "**/.gitignore"
jobs:
  # frontend:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: ./frontend
  #   steps:
  #     - name: Setup Node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: "16.x"
  #     - name: Checkout and fetch repo
  #       uses: actions/checkout@v3
  #     - name: Cache node modules
  #       id: cache-npm
  #       uses: actions/cache@v3
  #       env:
  #         cache-name: cache-node-modules
  #       with:
  #         path: ~/.npm
  #         key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
  #     - name: Install node packages
  #       run: npm ci
  #     - name: Build
  #       run: npm run build
  #     - name: Coyp toml file to dist folder
  #       run: cp netlify.toml dist/netlify.toml
  #     - name: Deploy to Netlify
  #       uses: netlify/actions/cli@master
  #       with:
  #         args: deploy --dir=frontend/dist --prod
  #       env:
  #         NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
  #         NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_DEPLOY_AUTH }}

  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: "salimiyahya50@gmail.com"
          appdir: "backend"
